# Generated by Django 4.0.1 on 2022-01-22 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerDataModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('login', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('phone', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='VotingModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.clientmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerVariantModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=64)),
                ('chosen', models.BooleanField()),
                ('answer_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.answerdatamodel')),
            ],
        ),
        migrations.AddField(
            model_name='answerdatamodel',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.votingmodel'),
        ),
    ]
