# Generated by Django 4.0.1 on 2022-01-24 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('login', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('phone', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='VotingModel',
            fields=[
                ('type', models.BooleanField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('owner_id', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AnswerVariantModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=64)),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.votingmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerHistoryModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('voting_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.clientmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerHistoryElementModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.answerhistorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerDataModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('voted_client_id', models.IntegerField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.answervariantmodel')),
            ],
        ),
    ]
